### ISSUE TITLE
try/catch for es6 require causing undesired logging

### ISSUE THREAD

**Issue by spalger** [bevry/ambi#4]
I'm using ambi by way of a several other modules and it appears that in node 0.10 simply requiring ambi causes error logging to the console:

![image](https://cloud.githubusercontent.com/assets/1329312/9743857/6081e178-561d-11e5-9f54-3b4fb0cd20b3.png)

Mind if I ask what the benefit of running code in es6 is when you already transpile to es5? Why not simply default to es5?

**Comment by balupton** [comment]
Thanks, there was another report of this over here too: https://github.com/docpad/docpad/issues/1007

The solution there was to drop node 0.10 support, which makes sense as it is years old and node v4 is around the corner. Which would entail unpublishing v2.3.0 as that was an unintended breaking change (if npm still lets you unpublish... not sure if it does), and release a new v3 that drops it.

**However,** I was able to find a fairly easy was of fixing that by adding a v8 engine check, which is now in the latest equivalent file in https://github.com/bevry/base - so will make an issue there, a trello card, and update the necessary packages that still use the old code.

> Mind if I ask what the benefit of running code in es6 is when you already transpile to es5? Why not simply default to es5?

Performance: https://github.com/bevry/es6-benchmarks

**Comment by balupton** [comment]
The above reasoning and code etc has been moved to https://github.com/bevry/esnextguardian

Ambi will be updated to use the latest esnextguardian in a few weeks.

**Comment by balupton** [comment]
Released v2.4.0 that should fix this. Thanks for reporting!
